### ISSUE TITLE
Schedule Weekly Project Meetings

### ISSUE THREAD

**Issue by ezampino** [data2health/data-quality#23]
Kari, 
Mehadi, 
Liz
Nicole W.

**Comment by ramussa** [comment]
This meeting has been scheduled for every 2 weeks effective 3/18, 3-4pm PST.

**Comment by ezampino** [comment]
Here is the notes from 03/18 meeting: https://docs.google.com/document/d/1Ghu_Y3VW8TdIk3ERrxJngv2THqjG2mpVa7SMOdt-uDU/edit

**Comment by ezampino** [comment]
Here are the notes from todays meeting (3/18) https://docs.google.com/document/d/1Ghu_Y3VW8TdIk3ERrxJngv2THqjG2mpVa7SMOdt-uDU/edit

Liz
